name: "deploy-s3-docker"
description: "Deploy to AWS S3"
inputs:
  bucket:
    description: "The name of the bucket to deploy to"
    required: false
    default: "my-bucket"
  bucket-region:
    description: "The region of the bucket to deploy to"
    required: false
    default: "us-east-1"
  dist-folder:
    description: "The folder to deploy"
    required: false
    default: "dist"
outputs:
  website-url:
    description: "The URL of the bucket"
runs:
  using: "docker"
  image: "Dockerfile"